# Generated by Django 2.0.3 on 2018-10-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerManagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classnum', models.CharField(max_length=5)),
                ('provider', models.CharField(max_length=5)),
                ('service', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=10)),
                ('system', models.CharField(max_length=15)),
                ('outside', models.CharField(max_length=15)),
                ('inside', models.CharField(max_length=15)),
                ('cpu', models.CharField(max_length=55)),
                ('memory', models.CharField(max_length=3)),
                ('disk', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
