# Generated by Django 2.0.3 on 2018-10-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManagent', '0002_auto_20181021_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=55)),
                ('type', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DBAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('address1', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60)),
                ('address3', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InsideName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('mac', models.CharField(max_length=17)),
                ('cpu', models.CharField(max_length=60)),
                ('mem', models.CharField(max_length=3)),
                ('disk', models.CharField(max_length=5)),
                ('system', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MailManagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
