# Generated by Django 2.0.3 on 2018-10-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManagent', '0003_accountmanagent_dbaccount_insidename_mailmanagent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmanagent',
            old_name='type',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='dbaccount',
            old_name='type',
            new_name='style',
        ),
    ]
