# Generated by Django 2.0.3 on 2018-10-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerManagent', '0004_auto_20181023_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermanagent',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
